name: Symbiotest

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  
jobs:
  code-security-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Scan
        uses: SymbioticSec/actions/scan@v0.4.2
        with:
          scan-type: code
          api-token: ${{ secrets.SYMBIOTIC_ORGA_TOKEN }}
          diff-scan: true
          

  
